project:
  type: book
  output-dir: docs

book:
  title: "Shamati"
  author: " Rav Yehuda Ashlag"
  translator: "Charles Kiefer"
  editor: "Charles Kiefer"
  date: "20/11/2022"
  language: "pt-br"
  chapters:
    - index.qmd
    - shamati1.qmd
    - shamati2.qmd
    - shamati3.qmd
    - shamati4.qmd
    - shamati5.qmd
    - shamati6.qmd
    - shamati7.qmd
    - shamati8.qmd
    - shamati9.qmd
    - shamati10.qmd
    - shamati11.qmd
    - shamati12.qmd
    - shamati13.qmd
    - shamati14.qmd
    - shamati15.qmd
    - shamati16.qmd
    - shamati17.qmd
    - shamati18.qmd
    - shamati19.qmd
    - shamati20.qmd
    - shamati21.qmd
    - shamati22.qmd
    - shamati23.qmd
    - shamati24.qmd
    - shamati25.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: journal
  pdf:
    documentclass: scrreprt

editor: visual

