# Alegria com Tremor
(Ouvi em Tav-Shin-Chet, 1947-1948)

::: {style="text-align: justify"}

A alegria é considerada amor, o qual é existência. É semelhante a quem constrói para si uma casa sem fazer nenhum buraco nas paredes. Você descobre que ele não pode entrar na casa, já que não há nenhum local oco nas paredes da casa pelo qual ele possa entrar. Portanto, um espaço vazio deve ser construído para que ele possa entrar na casa.

 

Assim, onde há amor deve haver também temor, pois o temor é o vazio. Em outras palavras, o indivíduo deve despertar o temor de que ele possa não ser capaz da intenção de doar.

 

Segue-se que, quando há ambos, há completude. Caso contrário, cada um deseja revogar o outro. Por essa razão, devemos tentar ter ambos no mesmo lugar.

 

Esse é o significado da necessidade do amor e do temor. O amor é chamado de existência, enquanto o temor é chamado de deficiência e de vazio. Apenas com os dois juntos é possível haver completude. Isso é chamado “duas pernas” porque, precisamente quando se tem duas pernas, o indivíduo consegue caminhar.

:::
