# Quais são as três coisas que ampliam a mente de alguém durante o Trabalho?
(Escutei em Elul, em agosto de 1942)

::: {style="text-align: justify"}

 O Sagrado Zohar interpreta a seguinte frase que nossos sábios escreveram: “Três coisas ampliam nossa mente: uma bela mulher, uma bela morada e belos **Kelim** (vasos)”. Quando diz “uma bela mulher” refere-se à Sagrada Shekiná (Divindade). “Uma bela morada” é o coração, e “belos **Kelim** são os órgãos.



Precisamos explicar que a Sagrada Shekiná não pode se manifestar em sua verdadeira forma, que é um estado de graça e de beleza, exceto quando a pessoa possui belos **Kelim**, que representam os “órgãos” recebidos do coração. Isto significa que a pessoa deve, em primeiro lugar, purificar seu coração para transformá-lo numa bela morada, anulando o desejo de receber para si mesmo, e acostumando-se a trabalhar em ações que em sua totalidade estejam governadas pela finalidade de outorgar. Dessa forma, são obtidos belos **Kelim**, isto é, que seus desejos, chamados **Kelim**, foram purificados da recepção para si mesmos. Agora, ao contrário, são puros e discernidos como outorgamento.



No entanto, se a morada não é bela, então o Criador declara: “Ele e Eu não podemos habitar embaixo do mesmo teto”. A razão disso é que deve haver equivalência de forma entre a Luz e o **Kli** (vaso). Desse modo, quando alguém assume e aceita a fé na pureza, tanto na mente quanto no coração, é recompensado com uma bela mulher, que se refere à Sagrada Shekiná, manifestando-se diante dele em graça e beleza. E isso amplia a sua mente.



Noutras palavras, através do prazer e do regozijo, a Sagrada Shekiná manifesta-se em suas entranhas, enchendo os seus **Kelim** externos e internos. Isso se obtém através da inveja, da luxúria e da honra que “afastam a pessoa do mundo”. Ao falar de inveja, refere-se à inveja a respeito da Sagrada Shekiná, relacionada com o ciúme, no mesmo sentido da frase “O ciúme do Senhor das Hostes”.  A honra significa que a pessoa deseja incrementar a Glória dos Céus. E a luxúria se diz em virtude de “Haveis escutado o desejo dos humildes”. 

:::
