# A Shechinah no Exílio
(Escutei em 1942)

<div style="text-align: justify">

O **Zohar** Sagrado diz: "Ele é **Shochen** (Morador) e Ela é **Shechinah** (Divindade)". Assim devemos interpretar essas palavras: É sabido que não há transformação alguma relativamente à Luz Superior (ela não muda). Assim está escrito: "Eu, o Senhor, não mudo". Todos os nomes e denominações dizem respeito somente aos Kelim (vasos), que consistem no desejo de receber incluído em Malchut, a raiz da Criação. Desde lá, ele desce até nosso mundo, até as criaturas.


Todos esses discernimentos, começando com Malchut, que é a raiz da criação dos mundos, até as criaturas, é denominado **Shechinah**. O Tikkun (correção) geral ocorrerá quando a Luz Superior brilhar nelas, nas criaturas, em plenitude e perfeição.

A Luz que brilha nos vasos se chama **Shochen**, e os vasos geralmente são chamados **Shechinah**. Em outras palavras, a **Luz reside dentro da** **Shechinah**. Isto quer dizer que a Luz é chamada **Shochen**, porque está dentro dos vasos; ou seja, que a totalidade (ou o conjunto) dos Kelim se chama **Shechinah**.


O tempo que precede o brilho da Luz nos Kelim em absoluta plenitude se chama **"Tempo de Correções"**. Isto significa que realizamos correções para que a Luz possa brilhar plenamente dentro dos vasos. Antes disto, esse estado é chamado **"Divindade no Exílio"**.



Isso significa que ainda não há perfeição nos Mundos Superiores. Abaixo, nesse mundo, deve existir um estado através do qual a Luz Superior se encontra dentro do desejo de receber. **Este Tikkun é considerado “receber com o fim de doar”**. Entretanto, o desejo de receber é preenchido de discernimentos desprezíveis e inúteis, que não honram aos Céus. Isto significa que o lugar em que o coração deveria ser um Tabernáculo para a Luz de Deus, se converte em um espaço de desperdícios e de sujeira. Em outras palavras, a vilania toma conta de todo o coração.

Isto se chama "Divindade no pó". Significa que ela é rebaixada ao nível do chão, e que todos desprezam tudo o que é relativo à Santidade, e que não existe nenhum desejo de retirá-la do pó. Ao invés disso, eles escolhem coisas desprezíveis, e isto gera tristeza à Shechina, porque a pessoa não constrói um lugar no coração que possa ser convertido em um Tabernáculo para a Luz Divina.

</div>
