# Lishmá é um despertar de Cima. E por que necessitamos de um despertar de Baixo?

::: {style="text-align: justify"}

 O recebimento de **Lishmá** (em benefício Dele) não é algo que esteja ao alcance de nosso entendimento, já que para a mente humana é inconcebível que algo assim possa existir em nosso mundo. Isto se deve a que a pessoa só tem permissão de entender que se ela observa **Torah** e **Mitvot** receberá algo. Nisso deve haver alguma recompensa, ela imagina; do contrário, ela não poderia fazer nada.



Por outro lado, **Lishmá** é uma iluminação que vem do Alto, e somente quem a recebe pode conhecer e compreender esse fenômeno. Sobre isso está escrito: “Prova e vê que o Senhor é bom”.



Assim, devemos entender porque uma pessoa deve buscar o conselho de como alcançar **Lishmá**. E, depois disso, ela deve entender que nenhum conselho será de qualquer utilidade quanto a isso. Se Deus não nos outorga outra natureza chamada de “o desejo de doar” nenhum trabalho poderá nos ajudar a alcançar **Lishmá**.

A explicação, segundo os nossos sábios, é: “Não depende de ti completar o trabalho; e não és livre para fugires dele” *(Pirket Avot 2: 21)*. Isso significa que a pessoa deve produzir o despertar de Baixo, já que isso se discerne como uma oração.



A oração representa uma carência e sem uma carência não pode existir preenchimento nenhum. Por fim, quando alguém sente a necessidade de trabalhar em **Lishmá**, esse preenchimento vem de Cima, e a resposta à oração vem de Cima, e a pessoa recebe o preenchimento da sua necessidade. Então, o trabalho da pessoa é necessário para receber **Lishmá** do Criador somente sob a forma de uma carência e um **Kli** (vaso). Não obstante, a pessoa jamais poderá alcançar esse preenchimento por si mesmo, mas unicamente como um presente que vem do Criador.



Por outro lado, a oração deve ser completa, ou seja, desde o mais fundo do coração; e a pessoa deve ter certeza absoluta de que não existe ninguém no mundo que possa ajudá-lo, exceto o Criador Ele Mesmo.



Ainda assim, como pode a pessoa saber que ninguém mais além do próprio Criador pode ajudá-la? A pessoa pode obter esse discernimento precisamente se já havia empregado todas as forças que tinha ao seu alcance sem conseguir nada. Portanto, a pessoa deve fazer todo o possível no mundo para lograr o nível de trabalho chamado Em benefício Dele. Somente então a pessoa consegue elevar uma prece do fundo de seu coração e ser ouvida pelo Criador.



Quando a pessoa está trabalhando em favor de **Lishmá** deve saber que precisa incorporar por completo a vontade de trabalhar unicamente com a intenção de doar, o que equivale a dizer que deve trabalhar somente para doar sem receber nada em troca. Somente nesse momento a pessoa começa a perceber que seus órgãos físicos se opõem a isso. A partir daí, a pessoa começa a ter uma clara noção de que não lhe resta outra alternativa a não ser transferir a sua demanda ao Criador e pedir-Lhe ajuda para que seu corpo aceite escravizar-se de modo incondicional diante Dele, já que a pessoa se dá conta de que não consegue persuadir seu corpo a anular-se por completo. Nesse momento, precisamente quando a pessoa descobre que não há razão para esperar que seu corpo concorde a trabalhar por si mesmo para o Criador, a oração surge do fundo do coração e acaba sendo aceita por Ele.



É preciso entender que ao alcançar **Lishmá** a pessoa mata a sua inclinação ao mal, que é o desejo de receber, e ao adquirir o desejo de doar todo o desejo de receber é cancelado. A isso se chama “matar o desejo de receber”. Porque foi retirado e porque não tem mais nada a fazer ao não estar mais em uso, quando sua função é revogada, considera-se que o desejo de receber foi morto.



Quando alguém analisa “que tipo de recompensa recebe o homem como resultado de todo o seu trabalho durante todo o tempo em que trabalhou sob o Sol”, ela descobre que não é tão difícil assim escravizar-se diante de Seu Nome por duas razões: de qualquer forma, seja voluntária ou involuntariamente, a pessoa precisa realizar todo o tipo esforços neste mundo. E o que é que sobra como resultado de todos esses esforços? No entanto, se a pessoa trabalha em **Lishmá** ela recebe muito prazer durante e através do trabalho em si.



Segundo o versículo “E não me invocaste a Mim, oh Jacó, nem tampouco de Mim te cansaste, oh Israel”, o maguid de Dubna disse que isso é similar ao caso do homem rico que saiu do trem e que levava consigo uma pequena maleta. Ele a colocou ali onde todos os comerciantes colocavam as suas bagagens. Os carregadores logo carregaram as malas e as levaram ao hotel onde os comerciantes estavam alojados. O carregador de malas pensou que o homem rico havia carregado a sua própria maleta e que não necessitava de seus serviços e por isso carregou somente uma mala grande.



O comerciante quis pagar pouco ao carregador, como era de seu costume, mas o homem não quis aceitar, e lhe disse: “Coloquei na entrada do hotel uma mala enorme que me deixou exausto, e foi a única que consegui carregar, e agora você quer me pagar com essa ninharia?”



A lição é que quando uma pessoa vem e diz que trabalhou de maneira exaustiva em observar **Torah** e **Mitvot**, o Criador retruca: “Tu não me invocaste, oh Jacó”. Noutras palavras, “a maleta que carregaste não foi a Minha, mas a de outra pessoa. Porque disseste que observar a **Torah** e as Mitzvot te custou muito esforço deves ter trabalhado para outro patrão. Por isso, procure-o, para que ele te pague”. Esse é o significado de “nem tampouco de Mim te cansastes, oh Israel”. Isso quer dizer que quem trabalha para o Criador não sente este trabalho como uma carga para si mesmo. Pelo contrário, esse trabalho lhe proporciona prazer e exaltação espiritual.



Por outro lado, quem trabalha com diferentes propósitos, não pode se dirigir ao Criador se queixando e Lhe exigindo que lhe proporcione vitalidade no trabalho, já que não está trabalhando para o Criador; e, portanto, não pode esperar pagamento. Em vez disso, a pessoa pode queixar-se para quem ela esteve trabalhando, para que lhe proporcione prazer e vitalidade.



E porque existem tantos propósitos em Lo **Lishmá** (não em benefício Dele), a pessoa deve exigir a quem trabalhou que lhe proporcione a devida recompensa, que consiste em prazer e vitalidade. Quanto a isso se diz o seguinte: “Semelhantes a eles são os que o fazem, e qualquer um que confia neles”.



É certo que isso nos causa perplexidade. Depois de tudo, vemos que mesmo quando alguém assume para si o Jugo dos Céus sem nenhuma outra intenção, mesmo assim não recebe uma sensação de vitalidade de tal forma que possa dizer que esta a empurra a assumir para si mesmo o Jugo dos Céus. E a única razão porque alguém assume essa carga se dá somente porque ela coloca a fé acima da razão. Noutras palavras, a pessoa faz isso superando a si mesma à força, contra a sua própria vontade. Assim, podemos perguntar o seguinte: “Por que a pessoa sente o esforço desse trabalho, com o corpo constantemente buscando o momento de se livrar disso, como quem não sentisse vitalidade alguma através desse trabalho? De acordo com o que foi dito anteriormente, quando alguém trabalha humildemente e tem somente o propósito de trabalhar com a intenção de doar, por que o Criador não lhe proporciona o sabor e a vitalidade implícitos no trabalho?



A resposta é que devemos entender que esse assunto representa uma grande correção. Se não fosse assim, se a Luz e a vitalidade tivessem brilhado de maneira instantânea quando começamos a realizar o trabalho do Reino dos Céus, teríamos recebido vitalidade no trabalho. Noutras palavras, o próprio desejo de receber teria concordado em executar o trabalho. Nesse estado, a pessoa, certamente, estaria de acordo, pois desejaria saciar esse desejo. Ou seja, estaria trabalhando em benefício próprio. E se esse fosse o caso, ela jamais poderia alcançar **Lishmá**. Isto se deve a que a pessoa estaria obrigada a trabalhar para seu próprio benefício, já que sentiria maior prazer no trabalho de Deus do que nos desejos corporais. Assim, a pessoa seria obrigada a permanecer em Lo **Lishmá**, já que desse modo poderia obter satisfação em seu trabalho. Ali onde há satisfação não há nada que a pessoa possa fazer, porque não poderia trabalhar sem a expectativa de uma recompensa. Então, se a pessoa recebesse satisfação através desse trabalho em Lo **Lishmá** teria que permanecer para sempre nesse estado. Isso seria parecido ao que se faz: quando muitas pessoas estão correndo atrás de um ladrão, ele também corre e grita “Pega, ladrão; pega, ladrão”. Desse modo, é impossível saber quem é o ladrão e é impossível prendê-lo e restituir ao dono o que foi roubado. Mas, quando o ladrão, que representa o desejo de receber, não sente o sabor e a vitalidade implícitos no trabalho de aceitar o Jugo dos Céus, e se nesse mesmo estado ele trabalha com a fé acima da razão, sob coação, e se o seu corpo acaba por se acostumar com esse trabalho contra seu próprio desejo de receber, então ele possui os meios para levar a cabo o trabalho que terá como propósito levar Contentamento ao Fazedor.



Isso tudo é assim porque o objetivo principal de uma pessoa é alcançar a Dvekut (adesão) com o Criador através de seu próprio trabalho, que se discerne como equivalência de forma, que é o estado em que todos os atos estão dirigidos somente à doação, tal como diz o versículo: “Então, te deleitarás no Senhor”. O sentido de “Então” é que, no começo do trabalho, a pessoa não recebe prazer. Muito ao contrário, no começo o trabalho é forçado.



No entanto, depois, quando a pessoa já se acostumou a trabalhar com a intenção de doar e a não examinar-se a si mesma para comprovar se está sentindo prazer ou não no trabalho, senão que acredita que está trabalhando para satisfazer o Fazedor, ela deve saber que o Criador aceita o trabalho dos inferiores sem se importar com quanto ou como este seja feito. Em absolutamente tudo, o Criador examina a intenção, e isso Lhe produz satisfação. Em conseqüência, à pessoa lhe é concedido o que diz o versículo: “Então, te deleitarás no Senhor”. Inclusive, sentirá prazer e deleite durante o trabalho de Deus, já que agora trabalha realmente para o Criador, pois o esforço que havia realizado durante o trabalho coagido lhe dá a capacidade de trabalhar para Ele de maneira sincera. Nesse instante, a pessoa descobre que também ali o prazer que ela recebe está vinculado ao Criador, isto é, é doado especificamente para o Criador.

:::
