# Não existe ninguém além Dele
(Escutei na Parashá Itro 1, em fevereiro de 1944)

<div style="text-align: justify"> 

Está escrito: “Não existe ninguém além Dele”. Isto significa que não existe nenhum outro poder no mundo capaz de se opor ao Criador. E a razão pela qual o homem vê que no mundo existem coisas e poderes que negam Seu Poder Absoluto deve-se, unicamente, a que o Criador assim o deseja. E este modo de correção se chama “a mão esquerda rejeita e a direita aproxima”. Isto é, aquilo que a esquerda rejeita é considerado uma correção. Isto significa que existem, no mundo, coisas que, desde o princípio, têm a finalidade de desviar o homem do caminho correto, por meio das quais ele é rejeitado da Kedushá (Santidade).

 

O benefício dessas rejeições consiste em que, por meio delas, a pessoa recebe uma necessidade e um desejo completo de que o Criador lhe ajude, pois vê que de outra forma estaria perdida. A pessoa não só não progride em seu trabalho, mas regride, isto é, faltam-lhe forças para observar a Torá e as Mitzvot, inclusive em Lo Lishmá (não em benefício Dele). Somente superando todos os obstáculos de maneira genuína, acima da razão, pode-se observar-se a Torá e as Mitzvot. Porém, nem sempre a pessoa possui a força necessária para elevar-se acima da razão, mas, ao contrário, encontra-se forçada a desviar-se da senda do Criador, Deus não o queira, ainda que em Lo Lishmá.

 

Aquele que sempre sente que os fragmentos são maiores que o todo, isto é, que existem muito mais descensos que ascensos, e que não vê um fim para esses estados, pensa que permanecerá para sempre à margem da Santidade, pois sente que lhe é demasiado difícil observar até mesmo uma vírgula da Torá, a menos que possa transcender acima da razão, mas nem sempre é capaz de consegui-lo.

 

Qual será o propósito de tudo isto?

 

É que, assim, ele chega a um momento em que finalmente compreende que ninguém pode ajudá-lo, exceto o próprio Criador. Isto leva a pessoa a fazer um sincero pedido para que o Criador lhe abra os olhos e o coração, de tal forma que consiga fazer a Dvekut. Disto se deduz que todas as rejeições que havia sentido provinham do próprio Criador. Isto significa que os descensos não foram motivados por falhas suas, ou porque ele não tivesse capacidade de sobrepor-se aos obstáculos. Ao contrário, às pessoas que verdadeiramente desejam acercar-se do Criador, e que não se contentam com ninharias, isto é, não permanecem sempre como crianças ignorantes, lhes será enviada ajuda do Alto, para que não possam dizer: “Graças a Deus, tenho Torá, Mitzvot e ações bondosas, por isso, o que mais posso necessitar?”

 

Somente a pessoa que possui um desejo sincero receberá ajuda do Alto. E a essa pessoa constantemente se lhe será mostrado o quão deficiente ainda é em seu atual estado. Isto significa que lhe serão enviados pensamentos e opiniões que estão em completa oposição a esse trabalho. A finalidade disso é fazê-la ver que não está unida ao Criador. E na medida em que consegue sobrepor-se a isso, acaba vendo sempre que se encontra ainda mais distante da Santidade que os demais, que se sentem unidos a Hashem.

 

O ser humano, como sabemos, sempre tem queixas e reclamações, e não consegue justificar o comportamento do Criador, e muito menos como Ele se comparta com respeito à própria pessoa. Por que não se sente unido ao Criador? No limite, chega a sentir que não participa da Santidade de forma alguma. Embora, às vezes, em algumas ocasiões, a pessoa receba um despertar do Alto, que a ajuda a reviver momentaneamente, em seguida, volta a cair ainda mais profundamente. No entanto, isto é o que a leva a descobrir que somente o Criador pode ajudá-la a acercar-se Dele. O homem deve sempre tratar de aferrar-se ao Criador. Isto significa que todos os seus pensamentos devem orientar-se para Ele, e mesmo que se encontre no pior estado, um estado do qual não se pode imaginar descenso maior, não deve abandonar Seu domínio. Isto é, não deve conceber que exista outra autoridade que lhe esteja impedindo de entrar na Santidade, e que seja capaz de causar-lhe benefício ou qualquer dano. Isto significa que não deve pensar que existe a força da Sitra Achra impedindo-o de executar boas ações e seguir a senda de Deus. Ao contrário, tudo é levado a cabo pelo Criador. Baal Shem Tov dizia que aquele que sustenta a existência de outra força no mundo, isto é, as klipot (cascas), se encontra no estado de “servir a outros deuses”. Não é necessariamente o pensamento herético o responsável pela transgressão. Porém, se ele crê que existe alguma outra autoridade e força além do Criador, desta forma já está cometendo um pecado. Mais ainda, aquele que sustenta que o homem é dono de sua própria autoridade e que afirma que foi ele mesmo quem ontem não desejou seguir a senda do Criador, também ele está cometendo uma heresia. Isto se dá porque ele não acredita que seja somente o Criador quem guia o mundo.

 

Sem dúvida, quando comete um pecado, certamente deve arrepender-se e lamentar-se por havê-lo cometido. Mas também aqui devemos colocar a dor e o sofrimento no lugar que se lhes corresponde, isto é, onde se encontra a causa desse pecado? Porque este é o ponto que se deve lamentar. Então, a pessoa deve arrepender-se e dizer: “Cometi esse pecado porque o Criador me arrojou da Santidade a um lugar de imundície, a uma latrina, a um lugar de sujeira”. Isto significa que o Criador lhe deu um desejo e um anelo para divertir-se e respirar o ar de um lugar pestilento.

 

(Aqui poderia se afirmar, como está escrito nos livros, que, às vezes, a pessoa encarna num porco. Devemos interpretar isto, como ele disse, entendendo que alguém recebe um desejo e um anelo de extrair vida daquelas coisas que considerava previamente como meros dejetos, mas agora deseja nutrir-se por meio delas).

 

Além disso, quando alguém sente que chegou a um estado de ascenso, e percebe bom sabor no trabalho, não deve dizer: “Agora encontro-me num estado no qual compreendo que vale a pena adorar o Criador”. Por outro lado, deve saber que nesse momento foi favorecido pelo Criador, e, portanto, Ele o acercou mais de Si Mesmo, e esta é a razão pela qual, nesse momento, percebe bom sabor no trabalho. E deve se cuidar de não abandonar o domínio da Santidade, afirmando que exista alguém mais que esteja operando além do Criador mesmo.

 

(Isto significa que ser favorecido pelo Criador, ao contrário, não depende da pessoa mesma, senão somente do Criador. E o homem, com sua mente externa, não pode compreender por que razão o Senhor o favoreceu nesse momento e não em outros).

 

Do mesmo modo, quando se lamenta de que o Criador não se acerca dele, também deve cuidar em que sentido lamenta esse distanciamento do Criador. Porque se o faz pensando em seu benefício pessoal, então, estaria se convertendo num receptor para si mesmo, para seu próprio benefício; e quem recebe está separado Dele. Ao contrário, deveria lamentar o exílio da Shekiná, pelo fato de estar causando aflição à Divindade.

 

Vejamos um exemplo. Um pequeno órgão de uma pessoa está dolorido. Certamente, essa dor é percebida, basicamente, na mente e no coração. O coração e a mente representam a totalidade do homem. E, logicamente, a sensação de um só órgão não pode ser equivalente a toda a sensação de dor de uma pessoa, que sente a maior parte da dor. 

 

Assim é a dor que o homem sente por estar afastado do Criador, já que o homem não é mais que um órgão particular da divina Shekiná, pois esta é a alma de Israel em sua totalidade. Portanto, a dor particular não se assemelha ao grau de dor geral.

Isto significa que existe aflição na Shekiná quando os órgãos estão apartados Dela, e quando Ela não pode sustentá-los.

(E poderíamos dizer que este é o significado do que disseram nossos sábios: “Quando um homem se arrepende, o que é o que diz a Shekiná? É mais leve do que a minha cabeça).

 

E se o homem não vincula a si mesmo o sofrimento por estar afastado do Criador, salva a si mesmo de cair no engano do desejo de receber “para si mesmo”, que é considerado

“separação da Santidade”.

 

O mesmo acontece quando alguém sente certa aproximação do estado de Santidade. Ou seja, quando sente alegria por ter sido favorecido pelo Criador. Também então a pessoa deve afirmar que seu prazer se deve, principalmente, a que agora existe deleite Acima, na sagrada Shekiná, porque esse pequeno órgão particular conseguiu acercar-se Dela, ao invés de afastar-se de Seu lado. E assim a pessoa obtém alegria do fato de ser recompensada com o poder de deleitar a Divindade. Isto está em concordância com o cálculo superior que diz que quando há deleite para o individual é apenas uma parte do deleite do total. Através desses cálculos, a pessoa perde sua individualidade e evita ser aprisionada pela Sitra Achra, que é o desejo de receber “em benefício próprio”.

 

Sem dúvida, o desejo de receber é necessário, pois dele está composto o homem em sua totalidade. Isto se deve a que qualquer coisa que exista numa pessoa, aparte o desejo de receber, não pertence à criatura, senão que se lhe atribui ao Criador. Porém, o desejo de receber prazer deve ser corrigido, transformando-se em doação. Isto significa que o prazer e o deleite que o desejo de receber consegue devem corresponder à intenção de brindar deleite Acima cada vez que a criatura sinta prazer, posto que este foi o propósito da criação: beneficiar às suas criaturas. E a isto se chama “o deleite da Shekiná, acima”.

 

Por essa razão, a pessoa deve encontrar instrução de como causar deleite Acima. E, certamente, se alguém recebe prazer, também Acima se sentirá contentamento e satisfação. Por isso, deseja estar sempre dentro do Palácio do Rei, e ser capaz de brincar com os tesouros do Rei. Isto, também, por suposto, provocará contentamento e satisfação Acima. Disto se depreende que todo o anelo deve estar orientado exclusivamente ao Criador e ao Seu deleite.

</div>
