# O que significa que a Sitra Achra seja chamada de “Malchut sem uma Coroa”?
(Ouvi em Tav-Shin-Aleph, 1940-1941, Jerusalém)

::: {style="text-align: justify"}

Coroa significa *Keter*, e *Keter* é o Emanador e a Raiz. A *Kedushá* [santidade] está conectada à raiz, ou seja, a *Kedushá* é considerada em equivalência de forma com sua raiz. Isso significa que, assim como a nossa Raiz, isto é, o Criador deseja apenas doar, como está escrito “Seu desejo de fazer o bem às criaturas”, também a *Kedushá* é destinada apenas para doar ao Criador.

 

A *Sitra Achra* [outro lado], no entanto, não é assim. Ela objetiva apenas receber para si mesma. Por essa razão, ela não está aderida à Raiz, isto é, *Keter*. É por isso que se faz a referência sobre a *Sitra Achra* não ter *Keter* [coroa]. Em outras palavras, ela não tem *Keter* porque ela está separada de *Keter*.

 

Agora podemos entender o que os nossos sábios disseram (*Sanhedrin* 29): “Todos que somam, subtraem”. Isso significa que, se você adiciona à conta, há subtração. Está escrito (Zohar Pekudei, item 249): “Ocorre o mesmo aqui, em relação ao que é interno, como está escrito, ‘Ademais, você deverá construir o tabernáculo com dez cortinas’. Em relação ao que é externo, está escrito ‘onze cortinas’, com adição de letras, ou seja, adicionando o *Ayin* [a letra hebraica adicionada] ao doze, e subtraindo da conta. Subtrai-se um do número doze devido à adição do *Ayin* ao doze”.

 

É sabido que o cálculo é implementado apenas em *Malchut*, o qual calcula a altura do grau (por meio da *Ohr Hozer* [luz refletida] nela). Além disso, é sabido que *Malchut* é chamada de “o desejo de receber para si mesmo”.

 

Quando ela anula seu desejo de receber perante a Raiz, e não quer receber, mas apenas doar à Raiz, assim como a Raiz que é o desejo do doar, então *Malchut*, chamada Ani [Eu], torna-se Ein [nada], com um *Aleph*. Apenas então ela estende a luz de *Keter* para construir seu *Partzuf* e se torna doze *Partzufim* de *Kedushá*.

 

Contudo, quando ela quer receber para si mesma, ela se torna o *Ayin* [olho] maldito. Em outras palavras, onde havia uma combinação de Ein, isto é a anulação perante a raiz, que é *Keter*, tornou-se *Ayin* (ou seja, ver e saber dentro da razão).

 

Isso é chamado “adição”. Significa que o indivíduo quer somar conhecimento à fé, e trabalhar dentro da razão. Em outras palavras, ela diz que vale mais a pena trabalhar dentro da razão e, então, o desejo de receber não terá objeção ao seu trabalho.

 

Isso causa uma falha, pois houve a separação de *Keter*, chamado de “o desejo de doar”, que é a Raiz. Não há mais a questão da equivalência de forma com a Raiz, chamada de *Keter*. Por essa razão, a *Sitra Achra* é chamada “*Malchut* sem coroa”. Isso significa que *Malchut* da *Sitra Achra* não tem Dvekut [adesão] com *Keter*. Por essa razão, eles só têm onze *Partzufim*, sem o *Partzuf* *Keter*.

 

Esse é o significado do que os nossos sábios disseram: “Noventa e nove morreram de mau olhado”. Ou seja, porque eles não têm a qualidade de *Keter*. Isso significa que a *Malchut* neles, o desejo de receber, não quer se anular perante a Raiz, chamada *Keter*. Isso significa que eles não fazem do Ani [Eu], chamado “desejo de receber”, uma qualidade do Ein [nada], que é o anulamento do desejo de receber.

 

Ao invés disso, eles querem somar. E isso é chamado “o *Ayin* [olho] maldito”. Ou seja, onde deveria haver Ein com *Aleph* [a primeira letra da palavra Ein], eles inserem o maldito *Ayin* [olho, a primeira letra da palavra]. Portanto, eles caem do seu nível devido à falta de Dvekut com a Raiz.

 

Esse é o significado do que os nossos sábios disseram: “Qualquer um que seja orgulhoso, diz o Criador, ‘ele e Eu não podemos habitar na mesma morada’”, pois assim o indivíduo cria duas autoridades. No entanto, quando o indivíduo está em um estado de Ein e se anula perante a Raiz, sendo que a sua única intenção é doar, como a Raiz, percebe-se que aqui há apenas uma autoridade – a autoridade do Criador. Então, tudo o que o indivíduo recebe no mundo é somente a fim de doar ao Criador.

 

Esse é o significado do que ele havia dito: “O mundo inteiro foi criado apenas para mim, e eu, para servir ao meu Fazedor.” Por essa razão, eu devo receber todos os níveis no mundo, a fim de que possa dar tudo ao Criador, o que é chamado de “servir ao meu Fazedor”.

:::
