# As coisas que vêm do coração
(Ouvi em 5 de Av, Tav-Shin-Dalet, 25 de julho de 1944, durante uma refeição comemorativa pela conclusão do Zohar)

::: {style="text-align: justify"}

Em relação às coisas que vêm do coração, entre no coração. Assim, por que vemos que um indivíduo ainda cai desse nível, mesmo se as coisas já entraram no coração?

 

Quando o indivíduo ouve as palavras da Torá de seu professor, ele imediatamente concorda com o professor e decide observar as palavras com coração e alma. Mas, depois, quando sai para o mundo, ele vê, cobiça e é infectado pela multidão de desejos que vagam pelo mundo. Então, ele e sua mente, seu coração e sua vontade são anulados diante da maioria.

 

Enquanto o indivíduo não tem o poder de sentenciar o mundo para o lado do mérito, o mundo o subjuga, ele se mistura com os desejos da multidão e é levado como uma ovelha para o abate. Ele não tem escolha. É compelido a pensar, querer, desejar e a exigir tudo o que a maioria demanda. Então, ele escolhe seus pensamentos estrangeiros e suas luxúrias e desejos repugnantes, os quais são estranhos à Torá. Nesse estado, ele não tem força para subjugar a maioria.

 

Ao invés disso, há então apenas um conselho: Apegar-se ao seu professor e aos livros. Isso é chamado “Da boca dos livros e da boca dos autores”. Apenas ao se apegar a eles o indivíduo pode mudar a sua mente - e isso será para melhor. No entanto, argumentos espertos não vão ajudá-lo a mudar a sua mente, mas apenas o remédio da Dvekut (adesão), pois essa é uma cura maravilhosa, já que a Dvekut o reforma.

 

Apenas enquanto o indivíduo está dentro da Kedushá (Santidade) ele pode argumentar consigo mesmo e se entregar a polêmicas inteligentes, de modo que a mente necessite que ele ande sempre no caminho do Criador. Porém, o indivíduo deve saber e gravar na sua mente que, mesmo quando ele é sábio e está certo de que já pode usar sua inteligência para derrotar a Sitra Achra (outro lado), tudo isso é inútil e que essa não é uma arma capaz de vencer a guerra contra a inclinação ao mal, pois todos esses conceitos não passam de uma consequência alcançada após a já mencionada Dvekut.

 

Em outras palavras, todos os conceitos sobre os quais ele constrói sua obra, dizendo que o indivíduo deve sempre seguir no caminho do Criador, são fundados na Dvekut com o professor. Portanto, se ele perde essa fundação, todos os conceitos se tornam impotentes, pois eles já não têm a fundação.

 

Dessa forma, o indivíduo não deve confiar na própria mente, mas deve aderir mais uma vez aos livros e aos autores, pois apenas isso pode ajudá-lo, e não o conhecimento ou o intelecto, visto que não há vitalidade neles.

:::
