# A questão do recebimento espiritual

::: {style="text-align: justify"}

 Logramos discernir muitos graus e aspectos diferentes nos Mundos Superiores. Devemos compreender que tudo o que se refere a graus e discernimentos trata apenas dos *attainments* das almas com respeito àquilo que elas recebem desses Mundos. Isto segue a regra de **Aquilo que nós não alcançamos, não conhecemos por nome algum**. Isto se deve a que a palavra nome indica um attainment, como ocorre com a pessoa que nomeia algum objeto depois de haver discernido sobre ele, de acordo com seu próprio entendimento. Enfim, a realidade em geral divide-se em três discernimentos sobre a questão do recebimento espiritual:



1. *Atzmuto* (Sua Essência)

2. *Ein Sof* (Infinito)

3. *Neshamot* (almas)  

<br>

1. De forma alguma discutimos o *Atzmuto*. Isto porque a raiz e o berço das criaturas começam no **Pensamento da Criação**, onde elas estão incorporadas, tal como está escrito: “A culminação de um ato se encontra no seu pensamento inicial”.



2. Ein Sof está relacionado com o **Pensamento da Criação**, que é “Seu desejo de fazer o bem as Suas criaturas”. Isto é considerado Ein Sof, e esta é a conexão que existe entre *Atzmuto* e as almas. Percebemos essa conexão sob a forma de “o Seu desejo de deleitar as suas criaturas”. Ein Sof é o começo. Chama-se “uma Luz sem Kli”. Não obstante, aqui se encontra a raiz das criaturas, que é a conexão entre o Criador e as criaturas, e que chamamos de “Seu desejo de fazer o bem às Suas criaturas”. Este desejo começa no mundo de Ein Sof e estende-se até o mundo de Assiyá, o nosso mundo.



3. As Neshamot (almas), que são as receptoras do bem que Ele deseja brindar.



Ele recebe o nome Ein Sof, porque essa é a conexão entre *Atzmuto* e as almas, a qual percebemos como “Seu desejo de fazer o bem às Suas criaturas”. Não temos expressão alguma para isso, exceto para essa conexão do desejo de desfrutar, e este é o começo desse vínculo chamado “Luz sem Kli”. E assim começa a raiz das criaturas; ou seja, a conexão entre o Criador e as criaturas, e que chamamos de “Seu desejo de fazer o bem as Suas criaturas”. Este desejo nasce no mundo de Ein Sof e se estende até o mundo de Assiyá.

Todos os mundos em si são considerados Luz sem Kli. Nesse sentido, não há nome nenhum para eles. São discernidos como *Atzmuto*, e neles não há recebimento.



Não pensemos que ali é possível captar muitos aspectos. Isto se deve a que esses discernimentos se encontram em potência. No entanto, assim que as almas chegam, esses discernimentos se manifestam nas almas que recebem as Luzes Superiores, conforme o que elas tenham arranjado e corrigido. Assim, as almas poderão receber, cada uma conforme a sua própria capacidade e qualificação.



Então, esses discernimentos se revelam de fato. Contudo, enquanto as almas não alcancem a Luz Superior os Mundos seguirão sendo considerados *Atzmuto*. Os Mundos são considerados Ein Sof, com respeito às almas que recebem dos Mundos. A razão disto é que tal conexão entre os Mundos e as almas, isto é, o que os Mundos dão às almas provém do **Pensamento da Criação**, que vem a ser a correlação entre as almas e *Atzmuto*. Esta conexão chama-se Ein Sof. Quando rezamos ao Criador, e lhe solicitamos que nos ajude, dando-nos o que desejamos, nos dirigimos ao nível de Ein Sof. Ali se encontra a raiz das criaturas, que busca distribuir-lhes prazer e deleite, o que chamamos de “Seu desejo de fazer o bem as Suas criaturas”.

  A oração é dirigida ao Criador que nos criou, e Seu Nome é “Seu desejo de fazer o bem as Suas criaturas”. Ele é chamado de Ein Sof porque se refere ao que antecede ao Tzimtzum (restrição). E ainda depois da restrição não ocorre nenhuma mudança Nele, posto que a Luz é imutável e Ele sempre conserva Seu Nome. A proliferação de Nomes se dá somente com respeito a quem recebe. Por isso, o primeiro Nome que se revelou, e que para as criaturas, representa a raiz, foi Ein Sof. E esse Nome permanece inalterado. Todas as restrições e mudanças sucedem unicamente com respeito a quem recebe, e Ele sempre resplandece no primeiro nome, que é Seu desejo infinito de fazer o bem as Suas criaturas.



Por tal motivo rezamos ao Criador, chamado Ein Sof, que ilumina sem restrição alguma e sem fim. E o que depois se converte no fim estriba nas correções para os receptores, com o propósito de que possam receber Sua Luz.



  A Luz Superior consiste em dois discernimentos: a pessoa que recebe e o recebido. Tudo o que dizemos a respeito da Luz Superior se refere somente à forma como a pessoa que recebe se impressiona com o que recebeu. Obviamente, nem a pessoa nem o recebido recebem por si só o nome de Ein Sof. Por outro lado, o recebido se denomina *Atzmuto*, e o sujeito da recepção se denomina “alma”, sendo esse um novo discernimento que é parte do todo. É novo no que diz respeito a que o desejo de receber está impresso ali. E, nesse sentido, a criação recebe o nome de “existência a partir da ausência”.

           

  Todos os Mundos em si são considerados uma unidade simples, e não há alteração na Santidade. Isto é o que significa “Eu, o Senhor, não mudo”. Não há Sefirot nem Bechinot (discernimentos) de nenhuma índole na Santidade. Nem mesmo os Nomes mais puros se referem à Luz em si, já que esta é um discernimento de *Atzmuto*, onde não há attainment. Por outro lado, todas as Sefirot e todos os discernimentos tratam somente daquilo que a pessoa percebe neles. Isto é assim porque o Criador quis que alcançássemos e que compreendêssemos a abundância como Seu desejo de fazer o bem às Suas criaturas.



  Para que pudéssemos alcançar aquilo que Ele havia desejado que alcançássemos e que compreendêssemos como é o Seu desejo de fazer o bem às Suas criaturas, Ele nos criou e nos conferiu os cinco sentidos, e esses sentidos obtém suas impressões da Luz Superior. Em conseqüência disso, recebemos muitos discernimentos, posto que o sentido geral chama-se “o desejo de receber”, e se divide em muitos aspectos, conforme a medida que os receptores sejam capazes de receber. Deste modo, encontramos muitas divisões e detalhes chamados ascensos e descensos, expansão, partida e etc. Devido a que o desejo de receber se denomina “criatura” e um “novo discernimento”, a palavra começa precisamente no lugar onde o desejo de receber começa a receber as impressões. A fala representa discernimentos, partes das impressões, pois aqui já existe uma correlação entre a Luz Superior e o desejo de receber. Isto se chama Luz e Kli. No entanto, não existe definição nem nome a respeito da Luz sem Kli, já que uma Luz que não seja alcançada por um receptor é considerada *Atzmuto*, sobre o qual é proibida qualquer declaração, posto que é inalcançável. Como poderíamos nomear e definir aquilo que não conseguimos alcançar?



Disto aprendemos que quando oramos para que o Criador nos envie salvação, cura e etc. há duas coisas que devemos distinguir:



1) O Criador;



2) Aquilo que provém Dele.



Sobre o primeiro discernimento, considerado *Atzmuto*, fica proibida toda e qualquer declaração, como acabamos de mencionar. No segundo discernimento, aquilo que provém Dele e que é considerado a Luz que se expande dentro de nossos vasos, isto é, dentro de nosso desejo de receber, é o que chamamos de Ein Sof. Representa a conexão do Criador com as criaturas, o que significa “Seu desejo de fazer o bem às Suas criaturas”. O desejo de receber é considerado como a Luz em expansão que finalmente alcança o desejo de receber. Quando o desejo de receber capta a Luz em expansão, esta adota o nome de Ein Sof. Chega aos receptores através de muitos véus, para que estes possam ser recebidos pelo inferior. Disso resulta que todos os discernimentos e todas as mudanças são levados a cabo especificamente no receptor, segundo o receptor se impressione com elas. Não obstante, devemos entender a matéria sobre a qual estamos falando. Quando falamos de discernimentos nos Mundos, referimo-nos a discernimentos potenciais. E quando o receptor alcança os ditos discernimentos, eles passam a ser discernimentos propriamente ditos.



O recebimento espiritual se dá quando o sujeito do recebimento e o alcançado se unem, já que sem um sujeito não pode existir forma para alcançá-lo, dado que não haveria quem obtivesse a forma do recebido. Por isso, este discernimento é considerado *Atzmuto*, a respeito do qual não é possível declaração alguma. Então, como podemos dizer que o alcançado tem sua própria forma? Só podemos falar se nossos sentidos se impressionam com a Luz em expansão, que é “Seu desejo de fazer o bem a Suas criaturas”, e que chega, de fato, às mãos dos receptores. De forma similar, quando examinamos uma mesa, nosso sentido do tato a percebe como algo duro. Também reconhecemos sua longitude e sua largura graças a nossos sentidos. Sem dúvida, isso implica que a mesa se manifeste dessa mesma forma a alguém que possua diferentes sentidos. Por exemplo: do ponto de vista de um anjo, se ele examinasse a mesa a veria de acordo com seus próprios sentidos. Portanto, não podemos determinar nenhuma forma a respeito do anjo, já que desconhecemos os sentidos que ele possui. Assim, dado que não podemos alcançar o Criador, é-nos impossível dizer que formas possuem os Mundos vistos de Sua perspectiva. Somente podemos alcançar os Mundos de acordo com os nossos próprios sentidos e sensações, já que esta foi Sua vontade para que a alcançássemos dessa maneira. Este é o sentido de “Não existe alteração alguma na Luz”. Por outro lado, todas as transformações ocorrem nos Kelim, isto é, nos nossos sentidos, de onde as medimos segundo a nossa própria imaginação. Nós medimos absolutamente tudo de acordo com nossa própria imaginação. Disto se conclui que se muitas pessoas examinassem um mesmo objeto ou entidade espiritual, cada um o compreenderia segundo a sua própria imaginação e sentidos, percebendo-o, cada um, de um modo diferente. Além disso, numa pessoa, a forma mudará conforme os seus próprios estados de ascensos e descensos, como já explicamos antes, ao dizer que a Luz é Luz Simples, e que todas as transformações e mudanças são levadas a cabo somente dentro de quem as recebe.



Oxalá a Luz nos seja concedida e que possamos seguir os caminhos do Criador, e servir-Lhe, já não com o propósito de receber uma recompensa em troca, mas com a finalidade de deleitá-Lo e assim elevar e resgatar a Divindade do pó.



Oxalá nos seja concedida essa adesão com o Criador e também a revelação de Sua Santidade às suas criaturas.
  
:::
